//! UUID v4 (random) and v7 (time-ordered) per RFC 4122 / RFC 9562.
//!
//! Scope:
//!   - v4: random UUID
//!   - v7: time-ordered random UUID (sortable, preferred for new systems)
//!   - parse / format in canonical 8-4-4-4-12 form
//!   - accessors: `version()`, `isRfc4122()`
//!
//! Out of scope (deliberately):
//!   - v1, v3, v5, v6, v8 (not widely needed; add only if a real use case appears)
//!   - non-canonical string formats (Microsoft brace form, urn:uuid: prefix)
//!   - database-specific types (use [16]u8 directly; don't add a `Uuid` SQL wrapper)
//!   - namespace/MAC/MD5/SHA1 (those are v3/v5 only — out of scope)
//!
//! Stability: API frozen at 0.1.0. New versions = new functions, never signature changes.

const std = @import("std");
const Random = std.Random;
const mem = std.mem;

/// UUID version (RFC 4122 / RFC 9562). Used for type-safe version checking
/// and for documenting which version a UUID was generated as.
///
/// Only versions v4 and v7 are generated by this lib. The full enum is
/// exposed so `parse()` can return all RFC 4122/9562-compliant versions.
pub const Version = enum(u4) {
    /// v1: time-based (MAC address + timestamp). Historical; not generated here.
    v1 = 1,
    /// v4: random. The workhorse version for new systems.
    v4 = 4,
    /// v7: time-ordered random (Unix epoch ms + random). Preferred for new
    /// systems needing sortability by creation time.
    v7 = 7,
};

/// 16-byte UUID, in big-endian byte order for the typed fields
/// (timestamp in v7, version nibble in byte 6, variant bits in byte 8).
///
/// Layout: `extern struct` with one field `bytes`. Frozen at 0.1.0.
pub const Uuid = extern struct {
    /// Raw 16 bytes. Index 0 = most significant byte of the timestamp
    /// (for v7), index 6 contains the version nibble in the high 4 bits,
    /// index 8 contains the variant bits in the high 2 bits.
    bytes: [16]u8,

    // ---------- Constructors ----------

    /// Generate a random v4 UUID.
    ///
    /// Requires a CSPRNG; use `std.crypto.random` or your platform's secure RNG
    /// at the call site. We require caller-provided `Random` so the function
    /// stays pure + explicit (no hidden state, easy to test).
    ///
    /// Example:
    /// ```
    /// var prng = std.Random.DefaultPrng.init(seed);
    /// const id = Uuid.v4(prng.random());
    /// ```
    pub fn v4(r: Random) Uuid {
        var self: Uuid = .{ .bytes = undefined };
        r.bytes(&self.bytes);
        // Version 4 → byte 6 high nibble = 0100
        self.bytes[6] = (self.bytes[6] & 0x0f) | 0x40;
        // Variant RFC4122 → byte 8 high two bits = 10
        self.bytes[8] = (self.bytes[8] & 0x3f) | 0x80;
        return self;
    }

    /// Generate a v7 UUID with an explicit timestamp.
    ///
    /// `ts_ms` is milliseconds since the Unix epoch. We require caller-provided
    /// timestamp (instead of calling `Io.Clock.now` or `posix.clock_gettime`
    /// inside) so the function stays explicit + clock-agnostic — Zig 0.16
    /// has no `std.time.milliTimestamp`.
    ///
    /// `ts_ms = 0` means "epoch start". Post-year-10889 timestamps overflow
    /// the 48-bit field.
    ///
    /// Example:
    /// ```
    /// // Use any clock source you trust:
    /// const ts: u64 = @divFloor(std.time.nanoTimestamp(), 1_000_000);
    /// const id = Uuid.v7At(rng, ts);
    /// ```
    pub fn v7At(r: Random, ts_ms: u64) Uuid {
        var self: Uuid = .{ .bytes = undefined };
        // Fill all 16 bytes with random first
        r.bytes(&self.bytes);
        // Overwrite first 6 bytes with 48-bit timestamp, big-endian
        mem.writeInt(u48, self.bytes[0..6], @truncate(ts_ms), .big);
        // Version 7 → byte 6 high nibble = 0111
        self.bytes[6] = 0x70 | (self.bytes[6] & 0x0f);
        // Variant RFC4122 → byte 8 high two bits = 10
        self.bytes[8] = (self.bytes[8] & 0x3f) | 0x80;
        return self;
    }

    // ---------- Parse / format ----------

    /// Error set for `parse`. Each variant maps to a specific validation failure.
    pub const ParseError = error{
        /// Input is not 36 chars (hyphenated) or 32 chars (compact).
        InvalidLength,
        /// A non-hex character appeared where hex was expected.
        InvalidHex,
        /// Version nibble (byte 6 high 4 bits) is not a valid RFC 4122/9562 value.
        /// Valid: 1, 3, 4, 5, 6, 7, 8. (v0, v2, v9-vF are reserved/invalid.)
        InvalidVersion,
        /// Variant bits (byte 8 high 2 bits) are not `10`. RFC 4122/9562
        /// require variant = 10xx. We don't accept NCS (00xx) or Microsoft
        /// (110x) backward-compat variants.
        InvalidVariant,
    };

    /// Parse a UUID from a string.
    ///
    /// Accepts:
    /// - Hyphenated canonical: 8-4-4-4-12, 36 chars, e.g. `"12345678-9abc-7ef0-8234-56789abcdef0"`
    /// - Compact non-hyphenated: 32 hex chars, e.g. `"123456789abc7ef0823456789abcdef0"`
    ///
    /// Case-insensitive on input. Validates version and variant bits per RFC
    /// 4122/9562. Rejects the all-zero "nil UUID" (variant = 00xx) and any
    /// non-RFC format.
    ///
    /// See `ParseError` for failure modes.
    ///
    /// Example:
    /// ```
    /// const id = try Uuid.parse("12345678-9abc-7ef0-8234-56789abcdef0");
    /// ```
    pub fn parse(s: []const u8) ParseError!Uuid {
        const Hyphenated = 36;
        const NonHyphenated = 32;

        if (s.len != Hyphenated and s.len != NonHyphenated) {
            return ParseError.InvalidLength;
        }

        // If hyphenated, check hyphen positions: 8, 13, 18, 23
        if (s.len == Hyphenated) {
            if (s[8] != '-' or s[13] != '-' or s[18] != '-' or s[23] != '-') {
                return ParseError.InvalidLength;
            }
        }

        var result: Uuid = .{ .bytes = undefined };
        var byte_idx: usize = 0;
        var i: usize = 0;
        while (i < s.len) : (i += 1) {
            // Skip hyphens in canonical form
            if (s.len == Hyphenated and (i == 8 or i == 13 or i == 18 or i == 23)) {
                continue;
            }
            // Need at least 1 more char for the low nibble
            if (i + 1 >= s.len) return ParseError.InvalidLength;
            const hi = hexValue(s[i]) orelse return ParseError.InvalidHex;
            const lo = hexValue(s[i + 1]) orelse return ParseError.InvalidHex;
            result.bytes[byte_idx] = (@as(u8, hi) << 4) | @as(u8, lo);
            byte_idx += 1;
            i += 1;
        }

        if (byte_idx != 16) return ParseError.InvalidLength;

        // Validate version (RFC 4122/9562 valid set: 1, 3, 4, 5, 6, 7, 8)
        const ver = result.bytes[6] >> 4;
        const ver_valid = (ver == 1) or (ver == 3) or (ver == 4) or (ver == 5) or (ver == 6) or (ver == 7) or (ver == 8);
        if (!ver_valid) return ParseError.InvalidVersion;

        // Validate variant (RFC 4122/9562: top 2 bits = 10)
        if ((result.bytes[8] & 0xc0) != 0x80) return ParseError.InvalidVariant;

        return result;
    }

    /// Write the canonical 8-4-4-4-12 lowercase hex string into any Writer.
    ///
    /// `w` is `anytype` for compatibility with both `*std.Io.Writer` (Zig 0.16+)
    /// and `*std.io.Writer` (legacy). Output is always lowercase, always with
    /// hyphens at the canonical positions (8, 13, 18, 23).
    ///
    /// Example (using Zig 0.16+ Io.Writer):
    /// ```
    /// var buf: [36]u8 = undefined;
    /// var w: std.Io.Writer = .fixed(&buf);
    /// try id.format(&w);
    /// // buf == "12345678-9abc-7ef0-8234-56789abcdef0"
    /// ```
    pub fn format(self: Uuid, w: anytype) !void {
        try writeHexBytes(w, self.bytes[0..4]);
        try w.writeByte('-');
        try writeHexBytes(w, self.bytes[4..6]);
        try w.writeByte('-');
        try writeHexBytes(w, self.bytes[6..8]);
        try w.writeByte('-');
        try writeHexBytes(w, self.bytes[8..10]);
        try w.writeByte('-');
        try writeHexBytes(w, self.bytes[10..16]);
    }

    // ---------- Accessors ----------

    /// Read the version nibble (byte 6 high 4 bits) as a `Version` enum.
    ///
    /// Returns the `Version` enum for valid version values (1, 3, 4, 5, 6, 7, 8).
    /// For invalid nibbles, `@enumFromInt` produces a "weird" enum value that
    /// won't match any declared variant — `switch` on the result will require
    /// an `else` branch.
    pub fn version(self: Uuid) Version {
        return @enumFromInt(self.bytes[6] >> 4);
    }

    /// Returns true if the variant bits (byte 8 high 2 bits) are `10xx`
    /// (RFC 4122 / RFC 9562 compliant).
    ///
    /// Useful when you have a `Uuid` from untrusted source (e.g., `parse`)
    /// and want to check it conforms to the modern standard rather than
    /// NCS (00xx) or Microsoft (110x) legacy variants.
    pub fn isRfc4122(self: Uuid) bool {
        return (self.bytes[8] & 0xc0) == 0x80;
    }
};

// ---------- File-private helpers ----------

/// Map a hex character to its numeric value. Returns null for non-hex.
/// Accepts both lowercase and uppercase hex digits.
fn hexValue(c: u8) ?u4 {
    return switch (c) {
        '0'...'9' => @intCast(c - '0'),
        'a'...'f' => @intCast(c - 'a' + 10),
        'A'...'F' => @intCast(c - 'A' + 10),
        else => null,
    };
}

/// Write `bytes` as lowercase hex into `w`. No separator.
fn writeHexBytes(w: anytype, bytes: []const u8) !void {
    const hex_chars = "0123456789abcdef";
    for (bytes) |b| {
        try w.writeByte(hex_chars[b >> 4]);
        try w.writeByte(hex_chars[b & 0x0f]);
    }
}
